{
  "Description": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.1 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, a different vulnerability than CVE-2010-3494.",
  "Severity": "MEDIUM",
  "Score": 4.3,
  "Cvss_v20_vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P"
}